import type { Catalog } from "./mcpCatalog.js";

/**
 * Curated MCP server catalog
 * Built from T0.1 verified entries (18 total)
 * For npx entries, "-y" is prepended to args to run without prompts
 */
export const CATALOG: Catalog = {
  version: 1,
  updatedAt: "2026-08-02",
  entries: [
    {
      id: "filesystem",
      name: "Filesystem",
      description: "Browse the file system",
      category: "files-and-git",
      homepage: "https://modelcontextprotocol.io",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-filesystem"],
      env: [],
      official: true,
      keywords: ["filesystem", "file", "directory", "read", "write"],
    },
    {
      id: "chrome-devtools",
      name: "Chrome DevTools",
      description: "Control Chrome through the DevTools Protocol",
      category: "browser",
      homepage: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
      command: "npx",
      args: ["-y", "chrome-devtools"],
      env: [],
      official: false,
      keywords: ["chrome", "browser", "devtools", "automation"],
    },
    {
      id: "server-memory",
      name: "Memory",
      description: "Enable memory for Claude through a knowledge graph",
      category: "memory",
      homepage: "https://modelcontextprotocol.io",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-memory"],
      env: [],
      official: true,
      keywords: ["memory", "knowledge graph", "context"],
    },
    {
      id: "playwright",
      name: "Playwright",
      description: "Control browsers with Playwright",
      category: "browser",
      homepage: "https://playwright.dev",
      command: "npx",
      args: ["-y", "@playwright/mcp"],
      env: [],
      official: true,
      keywords: ["playwright", "browser", "automation", "testing"],
    },
    {
      id: "github",
      name: "GitHub",
      description: "Interact with GitHub API",
      category: "files-and-git",
      homepage: "https://modelcontextprotocol.io",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-github"],
      env: [
        {
          key: "GITHUB_TOKEN",
          label: "GitHub personal access token",
          required: true,
        },
      ],
      official: true,
      keywords: ["github", "git", "api", "code"],
    },
    {
      id: "supabase",
      name: "Supabase",
      description: "Interact with Supabase databases",
      category: "databases",
      homepage: "https://github.com/supabase/mcp",
      command: "npx",
      args: ["-y", "@supabase/mcp-server-supabase"],
      env: [
        {
          key: "SUPABASE_URL",
          label: "Supabase project URL",
          required: true,
        },
        {
          key: "SUPABASE_API_KEY",
          label: "Supabase API key",
          required: true,
        },
      ],
      official: true,
      keywords: ["supabase", "database", "postgresql", "api"],
    },
    {
      id: "neon",
      name: "Neon",
      description: "Interact with Neon databases",
      category: "databases",
      homepage: "https://github.com/neondatabase/mcp-server-neon",
      command: "npx",
      args: ["-y", "@neondatabase/mcp-server-neon"],
      env: [
        {
          key: "NEON_API_KEY",
          label: "Neon API key",
          required: true,
        },
      ],
      official: true,
      keywords: ["neon", "database", "postgresql", "serverless"],
    },
    {
      id: "sqlite",
      name: "SQLite",
      description: "Access SQLite databases",
      category: "databases",
      homepage: "https://github.com/madnh/mcp-server-sqlite",
      command: "uvx",
      args: ["mcp-server-sqlite"],
      env: [],
      official: false,
      keywords: ["sqlite", "database", "sql"],
    },
    {
      id: "stripe",
      name: "Stripe",
      description: "Interact with Stripe API",
      category: "devtools",
      homepage: "https://github.com/stripe/ai",
      command: "npx",
      args: ["-y", "@stripe/mcp"],
      env: [
        {
          key: "STRIPE_API_KEY",
          label: "Stripe API key",
          required: true,
        },
      ],
      official: true,
      keywords: ["stripe", "payments", "api"],
    },
    {
      id: "cloudflare",
      name: "Cloudflare",
      description: "Interact with Cloudflare API",
      category: "devtools",
      homepage: "https://github.com/cloudflare/mcp-server-cloudflare",
      command: "npx",
      args: ["-y", "@cloudflare/mcp-server-cloudflare"],
      env: [
        {
          key: "CLOUDFLARE_API_TOKEN",
          label: "Cloudflare API token",
          required: true,
        },
      ],
      official: true,
      keywords: ["cloudflare", "cdn", "api", "infrastructure"],
    },
    {
      id: "notion",
      name: "Notion",
      description: "Access Notion databases and pages",
      category: "productivity",
      homepage: "https://github.com/makenotion/notion-mcp-server",
      command: "npx",
      args: ["-y", "@notionhq/notion-mcp-server"],
      env: [
        {
          key: "NOTION_API_KEY",
          label: "Notion API key",
          required: true,
        },
      ],
      official: true,
      keywords: ["notion", "database", "productivity", "api"],
    },
    {
      id: "brave-search",
      name: "Brave Search",
      description: "Search the web using Brave Search",
      category: "search-and-docs",
      homepage: "https://github.com/erik-balfe/brave-search",
      command: "npx",
      args: ["-y", "brave-search"],
      env: [
        {
          key: "BRAVE_SEARCH_API_KEY",
          label: "Brave Search API key",
          required: true,
        },
      ],
      official: false,
      keywords: ["search", "brave", "web", "api"],
    },
    {
      id: "context7",
      name: "Context7",
      description: "Query the Context7 API",
      category: "search-and-docs",
      homepage: "https://context7.com",
      command: "npx",
      args: ["-y", "context7"],
      env: [
        {
          key: "CONTEXT7_API_KEY",
          label: "Context7 API key",
          required: true,
        },
      ],
      official: false,
      keywords: ["context", "search", "api"],
    },
    {
      id: "figma",
      name: "Figma",
      description: "Access Figma files and designs",
      category: "productivity",
      homepage: "https://www.framelink.ai",
      command: "npx",
      args: ["-y", "figma-developer-mcp"],
      env: [
        {
          key: "FIGMA_API_TOKEN",
          label: "Figma API token",
          required: true,
        },
      ],
      official: false,
      keywords: ["figma", "design", "api"],
    },
    {
      id: "mcp-server-time",
      name: "Time Server",
      description: "Provides current time and timezone information",
      category: "productivity",
      homepage: "https://github.com/modelcontextprotocol/servers",
      command: "uvx",
      args: ["mcp-server-time"],
      env: [],
      official: true,
      keywords: ["time", "timezone", "date"],
    },
    {
      id: "fetch",
      name: "Fetch",
      description: "Fetch and browse web content",
      category: "search-and-docs",
      homepage: "https://github.com/modelcontextprotocol/servers",
      command: "uvx",
      args: ["mcp-server-fetch"],
      env: [],
      official: true,
      keywords: ["fetch", "http", "web", "scraping"],
    },
    {
      id: "git",
      name: "Git",
      description: "Execute Git commands in repositories",
      category: "files-and-git",
      homepage: "https://github.com/modelcontextprotocol/servers",
      command: "uvx",
      args: ["mcp-server-git"],
      env: [],
      official: true,
      keywords: ["git", "version control", "repository"],
    },
    {
      id: "tavily",
      name: "Tavily Search",
      description: "Search using Tavily API",
      category: "search-and-docs",
      homepage: "https://github.com/tavily-ai/tavily-js",
      command: "npx",
      args: ["-y", "@tavily/core"],
      env: [
        {
          key: "TAVILY_API_KEY",
          label: "Tavily API key",
          required: true,
        },
      ],
      official: true,
      keywords: ["tavily", "search", "api"],
    },
  ],
};
