import { isValidElement, useEffect, useState, type ReactNode } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { highlightCode, shikiThemeFor } from "../lib/markdown";
import { useTheme } from "../lib/theme";

type CodeProps = {
  className?: string;
  children?: ReactNode;
};

function codeText(children: ReactNode): string {
  if (typeof children === "string") {
    return children.replace(/\n$/, "");
  }
  if (Array.isArray(children)) {
    return children
      .map((child) => (typeof child === "string" ? child : ""))
      .join("")
      .replace(/\n$/, "");
  }
  return "";
}

function CodeBlock({ className, children }: CodeProps) {
  const code = codeText(children);
  const language = className?.replace("language-", "") ?? "plaintext";
  const { theme } = useTheme();
  const shikiTheme = shikiThemeFor(theme);
  const [html, setHtml] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    highlightCode(code, language, shikiTheme)
      .then((result) => {
        if (!cancelled) {
          setHtml(result);
        }
      })
      .catch((err) => {
        console.error("Failed to highlight code:", err);
        if (!cancelled) {
          setHtml(null);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [code, language, shikiTheme]);

  if (!html) {
    return (
      <pre className="overflow-x-auto rounded-lg bg-surface-raised p-4 font-mono text-sm text-text-muted ring-1 ring-border-subtle">
        <code>{code}</code>
      </pre>
    );
  }

  return (
    <div
      className="overflow-x-auto rounded-lg ring-1 ring-border-subtle [&_pre]:m-0 [&_pre]:bg-surface-raised [&_pre]:p-4"
      // HTML is generated by Shiki (syntax highlighter), not user input, so it's safe.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

function markdownCode(props: CodeProps) {
  const { className, children } = props;
  const isBlock = Boolean(className) || (typeof children === "string" && children.includes("\n"));

  if (isBlock) {
    return <CodeBlock className={className}>{children}</CodeBlock>;
  }

  return (
    <code className="rounded bg-surface px-1.5 py-0.5 font-mono text-[0.9em] text-accent ring-1 ring-border-subtle">
      {children}
    </code>
  );
}

type MarkdownViewProps = {
  content: string;
};

export function MarkdownView({ content }: MarkdownViewProps) {
  return (
    <article className="markdown-view">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          h1: ({ children }) => (
            <h1 className="border-b border-border-subtle pb-3 text-3xl font-semibold tracking-tight text-text">
              {children}
            </h1>
          ),
          h2: ({ children }) => (
            <h2 className="mt-9 scroll-mt-6 font-display text-xl font-semibold tracking-tight text-text">
              {children}
            </h2>
          ),
          h3: ({ children }) => (
            <h3 className="mt-8 scroll-mt-6 text-lg font-semibold text-text">{children}</h3>
          ),
          h4: ({ children }) => (
            <h4 className="mt-6 text-base font-semibold text-text">{children}</h4>
          ),
          p: ({ children }) => <p className="mt-4 leading-[1.75] text-text">{children}</p>,
          strong: ({ children }) => <strong className="font-semibold text-text">{children}</strong>,
          ul: ({ children }) => (
            <ul className="mt-4 list-disc space-y-2 pl-6 text-text marker:text-accent">
              {children}
            </ul>
          ),
          ol: ({ children }) => (
            <ol className="mt-4 list-decimal space-y-2 pl-6 text-text marker:text-accent">
              {children}
            </ol>
          ),
          li: ({ children }) => {
            const childList = Array.isArray(children) ? children : [children];
            const hasTask = childList.some((child) => {
              if (!isValidElement<{ type?: string }>(child)) {
                return false;
              }
              return child.props.type === "checkbox";
            });
            return (
              <li
                className={
                  hasTask
                    ? "list-none -ml-6 flex items-start gap-2 leading-[1.75] text-text"
                    : "leading-[1.75]"
                }
              >
                {children}
              </li>
            );
          },
          hr: () => <hr className="my-8 border-border-subtle" />,
          input: ({ type, checked, disabled }) =>
            type === "checkbox" ? (
              <input
                type="checkbox"
                checked={checked}
                disabled={disabled}
                readOnly
                className="mt-1 h-4 w-4 rounded border-border-subtle accent-accent"
              />
            ) : null,
          table: ({ children }) => (
            <div className="mt-6 overflow-x-auto rounded-lg ring-1 ring-border-subtle">
              <table className="min-w-full border-collapse text-left text-sm">{children}</table>
            </div>
          ),
          thead: ({ children }) => (
            <thead className="border-b border-border-subtle bg-surface-raised">{children}</thead>
          ),
          th: ({ children }) => <th className="px-4 py-3 font-semibold text-text">{children}</th>,
          td: ({ children }) => (
            <td className="border-t border-border-subtle px-4 py-3 text-text-muted">{children}</td>
          ),
          blockquote: ({ children }) => (
            <blockquote className="mt-4 rounded-lg bg-surface-raised px-4 py-3 text-text-muted ring-1 ring-border-subtle">
              {children}
            </blockquote>
          ),
          a: ({ href, children }) => (
            <a
              href={href}
              className="font-medium text-accent underline decoration-accent/40 underline-offset-4 hover:decoration-accent"
            >
              {children}
            </a>
          ),
          code: markdownCode,
          pre: ({ children }) => <>{children}</>,
        }}
      >
        {content}
      </ReactMarkdown>
    </article>
  );
}
